const works = [
  {
    id: Date.now() + Math.random().toString(36).substr(2, 9),
    img: "./projects/thumbnail/project-thumb-2.jpg",
    alt: "project_1",
    title: "Tic Tac Toe",
    tool: ["HTML", "CSS", "JavaScript"],
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores ex vel recusandae corrupti deleniti? Similique laborum reiciendis quis unde quia?",
    type: "Web Game",
    link: "./projects/tictactoe.html",
    github: "https://github.com/nauffal-code?tab=repositories",
  },
  {
    id: Date.now() + Math.random().toString(36).substr(2, 9),
    img: "./projects/thumbnail/project-thumb-3.jpg",
    alt: "project_2",
    title: "Snake Game",
    tool: ["HTML", "CSS", "JavaScript"],
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores ex vel recusandae corrupti deleniti? Similique laborum reiciendis quis unde quia?",
    type: "Web Game",
    link: "./projects/snakegame.html",
    github: "https://github.com/nauffal-code?tab=repositories",
  },
  {
    id: Date.now() + Math.random().toString(36).substr(2, 9),
    img: "./projects/thumbnail/project-thumb-1.jpg",
    alt: "project_3",
    title: "Memory Game",
    tool: ["HTML", "CSS", "JavaScript"],
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores ex vel recusandae corrupti deleniti? Similique laborum reiciendis quis unde quia?",
    type: "Web Game",
    link: "./projects/memorygame.html",
    github: "https://github.com/nauffal-code?tab=repositories",
  },
  {
    id: Date.now() + Math.random().toString(36).substr(2, 9),
    img: "./projects/thumbnail/project-thumb-4.png",
    alt: "project_4",
    title: "Wedding Invitation 1",
    tool: ["HTML", "CSS", "JavaScript", "Bootstrap"],
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores ex vel recusandae corrupti deleniti? Similique laborum reiciendis quis unde quia?",
    type: "Landing Page",
    link: "./projects/wedInv_1/wedInv_1.html",
    github: "https://github.com/nauffal-code?tab=repositories",
  },
  {
    id: Date.now() + Math.random().toString(36).substr(2, 9),
    img: "./projects/thumbnail/project-thumb-5.png",
    alt: "project_5",
    title: "Wedding Invitation 2",
    tool: ["HTML", "CSS", "JavaScript"],
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores ex vel recusandae corrupti deleniti? Similique laborum reiciendis quis unde quia?",
    type: "Landing Page",
    link: "./projects/wedInv_2/wedInv_2.html",
    github: "https://github.com/nauffal-code?tab=repositories",
  },
  {
    id: Date.now() + Math.random().toString(36).substr(2, 9),
    img: "./projects/thumbnail/project-thumb-6.png",
    alt: "project_6",
    title: "Color Flipper",
    tool: ["HTML", "CSS", "JavaScript"],
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores ex vel recusandae corrupti deleniti? Similique laborum reiciendis quis unde quia?",
    type: "Web App",
    link: "./projects/clr-flip.html",
    github: "https://github.com/nauffal-code?tab=repositories",
  },
  {
    id: Date.now() + Math.random().toString(36).substr(2, 9),
    img: "./projects/thumbnail/project-thumb-7.png",
    alt: "project_7",
    title: "Grocery Bud",
    tool: ["HTML", "CSS", "JavaScript"],
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores ex vel recusandae corrupti deleniti? Similique laborum reiciendis quis unde quia?",
    type: "Web App",
    link: "./projects/grocery.html",
    github: "https://github.com/nauffal-code?tab=repositories",
  },
];

export default works;
